# Generated by Django 5.1 on 2024-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(max_length=4)),
                ('empre_cliente', models.CharField(max_length=100)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('dir_cliente', models.CharField(max_length=50)),
                ('tel_cliente', models.CharField(max_length=50)),
            ],
        ),
    ]
