# Generated by Django 5.1 on 2024-08-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('can_maxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('can_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_producto', models.CharField(max_length=50)),
                ('descu_producto', models.CharField(max_length=50)),
                ('ubi_producto', models.CharField(max_length=4)),
            ],
        ),
    ]
